# Generated by Django 5.2.3 on 2025-07-04 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='birth_date',
            new_name='birthdate',
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(default='Sin biografía'),
        ),
    ]
